apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-admin-web
  namespace: system-msg
  labels:
   app: kafka-admin-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-admin-web	
  template:
    metadata:
      labels:
        app: kafka-admin-web
    spec:
      containers:
      - name: kafka-admin-web
        image: hlebalbau/kafka-manager:latest
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: "zoo1:2181,zoo2:2181"
        - name: APPLICATION_SECRET
          value: "random-secret"
        - name: KAFKA_MANAGER_AUTH_ENABLED
          value: "true"
        - name: KAFKA_MANAGER_USERNAME
          value: "admin"
        - name: KAFKA_MANAGER_PASSWORD
          value: "21121986"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-admin-web
  namespace: system-msg
spec:
  type: NodePort
  ports:
    - targetPort: 9000
      port: 9000
      nodePort: 30090
  selector:
    app: kafka-admin-web
