apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-controlcenter
  namespace: system-msg
  labels:
   app: kafka-admin-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-controlcenter	
  template:
    metadata:
      labels:
        app: kafka-controlcenter
    spec:
      containers:
      - name: kafka-admin-web
        image: confluentinc/cp-enterprise-control-center:latest
        ports:
        - containerPort: 9021
        env:
        - name: bootstrap.servers
          value: "kaf1:9092,kaf2:9092,kaf3:9092"
        - name: zookeeper.connect
          value: "zoo1:2181,zoo2:2181"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-controlcenter
  namespace: system-msg
spec:
  type: NodePort
  ports:
    - targetPort: 9021
      port: 9021
      nodePort: 30021
  selector:
    app: kafka-controlcenter
